sudo: false
language: go
go: 1.6

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
  - ./setup.sh

script:
  - ./test.sh
  - ./build.sh all

# after_success:
#   - bash <(curl -s https://codecov.io/bash)

# before_deploy:
#   - sha256sum temple_* > checksums.sha256

# deploy:
#   skip_cleanup: true
#   provider: releases
#   file:
#     - checksums.sha256
#     - temple_darwin_amd64
#     - temple_freebsd_arm
#     - temple_linux_386
#     - temple_linux_amd64
#     - temple_linux_arm
#     - temple_linux_ppc64le
#     - temple_netbsd_arm
#     - temple_windows_386.exe
#     - temple_windows_amd64.exe
#   on:
#     tags: true
#     repo: docwhat/temple
